### ISSUE TITLE
High memory usage during build

### ISSUE THREAD

**Issue by holly-hacker** [ovlach/nix-orca-slicer#8]
Building the flake seems to consume more than 25gb of memory, which causes out-of-memory issues on my 32gb machine. Is this expected behavior? I'm not too familiar with GCC memory usage on projects of this size.

**Comment by DeeKahy** [comment]
This happens for a lot of projects because unused memory is wasted memory, especially projects this large.

**Comment by holly-hacker** [comment]
Sure, but it becomes an issue when it's trying to use memory that's not there.

This is a relatively old issue and I'm currently not using it, so I'm closing this.
